"""LunaClaw Brief — Core Data Models

Defines the canonical data structures flowing through the pipeline:
  Item → ScoredItem → ReportDraft → QualityResult

All models are immutable-friendly dataclasses with auto-computed fields.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Item:
    """Unified content item produced by every Source adapter.

    Attributes:
        title:        Headline / repo name / paper title.
        url:          Canonical link.
        source:       Source identifier ("github", "arxiv", "finnews", …).
        raw_text:     Abstract / description / summary (≤500 chars).
        published_at: ISO-8601 timestamp string (may be empty).
        meta:         Source-specific metadata (stars, points, alternatives…).
        item_id:      SHA-256 fingerprint for deduplication.
    """

    title: str
    url: str
    source: str
    raw_text: str
    published_at: Optional[str] = None
    meta: dict = field(default_factory=dict)
    item_id: str = ""

    def __post_init__(self):
        if not self.item_id:
            self.item_id = self._compute_id()

    def _compute_id(self) -> str:
        normalized = f"{self.title.lower().strip()}|{self.source}|{self.url}"
        return hashlib.sha256(normalized.encode()).hexdigest()[:16]


@dataclass
class ScoredItem:
    """Item after multi-dimensional scoring.

    Attributes:
        item:  The original Item.
        score: Composite score (higher = more relevant).
        tags:  Domain tags assigned by Scorer (e.g. ["CV", "OCR"]).
    """

    item: Item
    score: float
    tags: list = field(default_factory=list)


@dataclass
class ReportDraft:
    """Markdown draft generated by an Editor (LLM).

    Attributes:
        markdown:      Raw Markdown content.
        issue_label:   Date-based label (e.g. "2026-03-17" or "03.10~03.16").
        word_count:    Character count (auto-computed).
        quality_score: Set after QualityChecker evaluation.
    """

    markdown: str
    issue_label: str
    word_count: int = 0
    quality_score: float = 0.0

    def __post_init__(self):
        self.word_count = len(self.markdown)


@dataclass
class QualityResult:
    """Result of QualityChecker validation.

    Attributes:
        passed: True if quality score ≥ threshold.
        score:  Normalized score in [0, 1].
        issues: Human-readable list of problems found.
    """

    passed: bool
    score: float
    issues: list = field(default_factory=list)


@dataclass
class ReportRequest:
    """Normalized report request parsed from user input.

    Decouples "what the user asked for" from "which preset to use",
    enabling topic × period routing and unknown-topic handling.
    """

    topic: str          # normalized topic key ("ai", "finance", "stock_a", …)
    period: str         # "daily" | "weekly"
    focus: str = ""     # optional sub-focus from user hint (e.g. "腾讯和阿里")
    raw_hint: str = ""  # original user input
    preset_name: str = ""  # resolved preset name (may be empty if no match)
    confidence: float = 1.0  # routing confidence (1.0 = exact match)
    auto_created: bool = False  # True if preset was auto-generated for unknown topic


@dataclass
class PresetConfig:
    """Full configuration for a report type (preset).

    A preset defines everything the pipeline needs: which sources to fetch,
    how to score, which editor to invoke, quality thresholds, and template.
    """

    name: str
    display_name: str
    cycle: str
    editor_type: str

    # Data sources
    sources: list
    time_range_days: int
    max_items: int

    # Scoring weights
    domain_keywords: dict
    source_weights: dict
    low_value_keywords: list

    # Editor config
    sections: list
    target_word_count: tuple
    tone: str

    # Quality thresholds
    min_sections: int = 4
    min_word_count: int = 2000

    # Deduplication
    dedup_window_days: int = 30

    # Rendering
    template: str = "report"

    # Metadata
    description: str = ""
    show_disclaimer: bool = False

    # Agent routing: topic family identifier for intent-based matching
    topic: str = ""
